<?php
/**
 * Invoice Template
 *
 * @since 1.0.0
 * @alter 1.1.0
 * 
 * Please do not edit this file, to create a custom invoice template:
 * 1. Copy the template folder to your current wordpress theme
 * 2. rename the folder to "invoice"
 *
 **/
 
if ( have_posts() ) : while ( have_posts() ) : the_post(); 
	
	global $payment_gateway_account;
	
	$payment_gateway_name = sh_get_payment_gateway();
	$payment_gateway_name = str_replace(' ', '', $payment_gateway_name);
	
	$payment_gateway_account = sh_get_payment_gateway_account();
	$payment_status = sh_get_invoice_status();
	$invoice_type = sh_get_invoice_type();
	
	if($payment_gateway_name != 'None' && $payment_gateway_account){
		$pay_ready = true;
	} else{
		$pay_ready = false;
	}

/**
 * Get the client ID and send it into our menu.
 * This creates the correct Dashboard link 
 *
 * We are also setting the sh_client_id Cookie
 *
 * @since 1.0
 **/
$terms = get_the_terms($post->ID , 'client');
$query_term = false;
if($terms)
{	
	$terms = array_values($terms);
	$query_term = $terms[0]->term_id;
		
}

if($query_term){

	$url = get_site_url();
	$url = parse_url($url);
	$domain = $url['host'];
	$path = $url['path'];
	
	if(!isset($_COOKIE['sh_client_id'])){
		setcookie('sh_client_id', $query_term, 25920000 + time(),'/');
	} elseif($_COOKIE['sh_client_id'] != $query_term){
		setcookie('sh_client_id', $query_term, 25920000 + time(), '/');
	}
}

// Display navigation menu
get_header(); sh_get_menu($query_term); 
?>
	
	<header>
		<section class="mini">
			<p><?php _e('Issued:', 'sh_invoice'); ?> <?php echo get_the_date(); ?></p>
			<h1><?php echo $invoice_type; ?></h1>
		</section>
		
		<section class="mini last">
			<p><?php _e('Unique ID:', 'sh_invoice'); ?></p>
			<h1>#<?php sh_invoice_number(); ?></h1>
		</section>
		
		<section class="controls">
			<div class="left-side">
				<a href="javascript:print()" class="print"><?php _e('Print', 'sh_invoice'); ?></a>
			</div>
			
		<?php if($pay_ready && $payment_status != 'Paid' && $invoice_type != 'Quote'):
			
			get_template_part( 'functions/invoice/gateways/'.$payment_gateway_name, 'single' );
				
		elseif($payment_status == 'Paid'): ?>
			<div class="btn">
				<?php _e('Invoice Paid', 'sh_invoice'); ?>
			</div>
		<?php elseif($invoice_type == 'Quote' && sh_get_quote_approved() == 'Not yet'): ?>
			<a href="<?php echo add_query_arg('approved', 'yes', get_permalink($post->ID)); ?>" class="btn"><?php _e('Approve', 'sh_invoice'); ?></a>
		<?php elseif(sh_get_quote_approved() != 'Not yet'): ?>
			<div class="btn">
				<?php _e('Quote Approved', 'sh_invoice'); ?>
			</div>
		<?php endif; ?>
            
		</section>
	</header><!-- #invoice-header -->

	<?php if(!$pay_ready && current_user_can('manage_options') ): ?>
		<section class="alert">
			<p><strong><?php _e( 'Warning:', 'sh_invoice' ); ?></strong> <?php _e( 'Payment account options have not been set. You will not receive payments until you set these, under Invoices &raquo; Options.', 'sh_invoice' ); ?></p>
		</section>
	<?php endif; ?>
	
	<section id="to-from"<?php if($payment_status == 'Paid'){ echo ' class="paid-status"'; }?>>
			
		<div class="alignleft g4">
			<aside><?php _e('To:', 'sh_invoice'); ?></aside>
			<div class="info">
				<?php if(sh_get_invoice_client_name()) { ?><strong><?php sh_invoice_client(); ?></strong><br /><?php } ?>
				<?php if(sh_get_invoice_client_business()) { ?><?php sh_invoice_client_business(); ?><br /><?php } ?>
				<?php if(sh_get_invoice_client_business_address()) { ?><?php sh_invoice_client_business_address(); ?><br /><?php } ?>
				<?php if(sh_get_invoice_client_phone()) { ?><?php sh_invoice_client_phone(); ?><br /><?php } ?>
				<?php if(sh_get_invoice_client_email()) { ?><?php sh_invoice_client_email(); ?><?php } ?>
			</div><!-- # info -->
		</div><!-- # TO -->
		
		<div class="alignright g4 last">
			<aside><?php _e('From:', 'sh_invoice'); ?></aside>
			<div class="info">
				
				<?php
				$company = sh_invoice_get_option('sh_invoice_company');
				$address = sh_invoice_get_option('sh_invoice_company_address');
				$phone = sh_invoice_get_option('sh_invoice_company_phone');
				?>
				
				<?php if($company){ ?>
					<strong><?php echo $company; ?></strong><br />
				<?php }
				if($address) { 					
					echo nl2br($address).'<br/>';
				} if($phone) { 					
					echo "$phone <br/>";
				}
				sh_invoice_email();?>
			</div><!-- # info -->
		</div><!-- # FROM -->
		
	</section><!-- #to-from -->
	
	<?php if(sh_invoice_has_details()): ?>
	<table class="invoice">
		<thead>
			<tr>
				<th class="item"><?php _e('Item', 'sh_invoice'); ?></th>
				<th class="type"><?php _e('Type', 'sh_invoice'); ?></th>
				<th class="rate"><?php _e('Rate', 'sh_invoice'); ?></th>
				<th class="quantity"><?php _e('Quantity', 'sh_invoice'); ?></th>
				<th class="sub-total"><?php _e('Sub-total', 'sh_invoice'); ?></th>
			</tr>
		</thead>
		<tbody>
			<?php while(sh_invoice_detail()): ?>
			<tr>
				<td class="item"><?php sh_the_detail_title(); ?> <span class="description"><?php sh_the_detail_description(); ?></span></td>
				<td><?php sh_the_detail_type(); ?></td>
				<td><?php sh_the_detail_rate(); ?><?php if(sh_get_the_detail_type() == 'Timed'){ _e(' / hr', 'sh_invoice'); } ?></td>
				<td><?php sh_the_detail_duration(); ?></td>
				<td><?php sh_the_detail_subtotal(); ?></td>
			</tr>
			<?php endwhile; ?>
		</tbody>
	</table>
	<?php endif; ?>
	
	<?php if($post->post_content): ?>
		<div class="notes g7">
			<h2><?php _e('Notes:', 'sh_invoice'); ?></h2>
			<?php the_content(); ?>
		</div>
	<?php endif; ?>
	
	<div class="summary">
		<div class="row">
			<div class="title"><?php _e('Sub-total', 'sh_invoice'); ?></div>
			<div class="figure"><?php the_invoice_subtotal(); ?></div>
		</div>
		
		<div class="row">
			<div class="title"><?php _e('Tax', 'sh_invoice'); ?></div>
			<div class="figure"><?php the_invoice_tax(); ?></div>
		</div>
		
		<div class="row total">
			<div class="title"><?php _e('Amount Due', 'sh_invoice'); ?></div>
			<div class="figure"><?php the_invoice_total(); ?></div>
		</div>
		
		<?php if($pay_ready && $payment_status != 'Paid' && $invoice_type != 'Quote'):
			get_template_part( 'functions/invoice/gateways/'.$payment_gateway_name, 'single' );
		elseif($payment_status == 'Paid'): ?>
			<div class="btn">
				<?php _e('Invoice Paid', 'sh_invoice'); ?>
			</div>
		<?php elseif($invoice_type == 'Quote' && sh_get_quote_approved() == 'Not yet'): ?>
			<a href="<?php echo add_query_arg('approved', 'yes', get_permalink($post->ID)); ?>" class="btn"><?php _e('Approve', 'sh_invoice'); ?></a>
		<?php elseif(sh_get_quote_approved() != 'Not yet'): ?>
			<div class="btn">
				<?php _e('Quote Approved', 'sh_invoice'); ?>
			</div>
		<?php endif; ?>
	</div>
	
<?php endwhile; else: ?>
	
	<header>
		<section class="mini last">
			<p><?php _e('Not Found', 'sh_invoice'); ?></p>
			<h1>Invoice</h1>
		</section>
	</header><!-- #invoice-header -->
	
	<section class="page-entry">
		<h2><?php _e("Invoice Not Found", "sh_invoice"); ?></h2>
		<p><?php _e("We're sorry, but that invoice doesn't seem to exist.", "sh_invoice"); ?></p>
	</section>
	
<?php endif; ?>

<?php get_footer(); ?>